import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';

import { ThemeProvider } from '@/components/Providers/ThemeProvider/ThemeProvider';

import './globals.css';

import { StorageKey } from '@/constants/app';

import AppInitializer from '@/components/AppInitializer/AppInitializer';
import Navbar from '@/components/Navbar/Navbar';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          storageKey={StorageKey.Theme}
        >
          <Navbar />
          <div className="container mx-auto flex min-h-screen flex-col px-4 sm:px-6 lg:px-8">
            <main className="flex-grow py-6">
              <AppInitializer />
              {children}
            </main>
            <footer className="mt-auto py-4 text-center text-gray-500">
              <p>&copy; {new Date().getFullYear()} playlistr</p>
            </footer>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
